// Bundles the WebView page (core engine + CSS + bridge entry) into a single
// self-contained HTML string, exported as an ESM module the RN component
// imports. Run via `npm run build` (also runs automatically on prepack).

import { build } from 'esbuild'
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const pkg = join(here, '..')

const result = await build({
  entryPoints: [join(pkg, 'src/webview-entry.js')],
  bundle: true,
  write: false,
  format: 'iife',
  target: ['es2020'],
  minify: true,
  outdir: 'out',
  loader: { '.css': 'css' },
})

let js = ''
let css = ''
for (const f of result.outputFiles) {
  if (f.path.endsWith('.js')) js = f.text
  else if (f.path.endsWith('.css')) css = f.text
}
if (!js) throw new Error('esbuild produced no JS output')

const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
<style>
html, body { margin: 0; padding: 0; width: 100%; height: 100%; overflow: hidden; overscroll-behavior: none; }
#board { position: fixed; inset: 0; }
${css}</style>
</head>
<body>
<div id="board"></div>
<script>${js.replaceAll('</script', '<\\/script')}</script>
</body>
</html>`

const out = join(pkg, 'src/board-html.generated.js')
mkdirSync(dirname(out), { recursive: true })
writeFileSync(
  out,
  '// GENERATED by scripts/build-html.mjs — do not edit.\n' +
  'export const BOARD_HTML = ' + JSON.stringify(html) + '\n'
)
console.log(`wrote ${out} (${(html.length / 1024).toFixed(1)} kB)`)
